stages:
  convert_tags:
    cmd: asv check && python tags_to_sha.py
    deps:
    - tags.txt
    - tags_to_sha.py
    outs:
    - hashes.txt
  run_benchmarks:
    cmd: asv update && asv run --quick --skip-existing-successful
    deps:
    - hashes.txt
    outs:
    - results:
        persist: true
        cache: false
